In [12]:
import numpy as np
M = [[1,0,3],[3,7,2],[2,-2,8],[0,-1,1],[5,8,7]]
M = np.array(M, dtype = float)

# a)
print ("a)")
MTM = np.dot(np.transpose(M),M)
MMT = np.dot(M,np.transpose(M))

print ("MTM:\n",MTM)
print ("MMT:\n",MMT)
print ("\n")

eigvalueA, eigvectorA = np.linalg.eig(MTM)
eigvalueB, eigvectorB = np.linalg.eig(MMT)

# b)
print ("b)")
print ("eigvalueA:\n",eigvalueA)
print ("eigvalueB:\n",eigvalueB)
print ("\n")

# c)
print ("c)")
print ("eigvectorA:\n",eigvectorA)
print ("eigvectorB:\n",eigvectorB)
print ("\n")

a)
MTM:
 [[  39.   57.   60.]
 [  57.  118.   53.]
 [  60.   53.  127.]]
MMT:
 [[  10.    9.   26.    3.   26.]
 [   9.   62.    8.   -5.   85.]
 [  26.    8.   72.   10.   50.]
 [   3.   -5.   10.    2.   -1.]
 [  26.   85.   50.   -1.  138.]]


b)
eigvalueA:
 [  2.14670489e+02   9.32587341e-15   6.93295108e+01]
eigvalueB:
 [  2.14670489e+02  -8.88178420e-16   6.93295108e+01  -3.34838281e-15
   7.47833227e-16]


c)
eigvectorA:
 [[ 0.42615127  0.90453403 -0.01460404]
 [ 0.61500884 -0.30151134 -0.72859799]
 [ 0.66344497 -0.30151134  0.68478587]]
eigvectorB:
 [[-0.16492942 -0.95539856  0.24497323 -0.54001979 -0.78501713]
 [-0.47164732 -0.03481209 -0.45330644 -0.62022234  0.30294097]
 [-0.33647055  0.27076072  0.82943965 -0.12704172  0.2856551 ]
 [-0.00330585  0.04409532  0.16974659  0.16015949  0.43709105]
 [-0.79820031  0.10366268 -0.13310656  0.53095405 -0.13902319]]




d)Due to caclulation error, we only take the first and the third eigenvalues. Correspondingly, we only take the first and the third columns of left singular vector and right singular vector.

In [11]:
s =np.diag([x**(0.5) for x in eigvalueA[::2]])
u=np.array([x[:3:2] for x in eigvectorB])
v=np.array([x[:3:2] for x in eigvectorA])
print ("U:\n",u)
print ("S:\n",s)
print ("V^T:\n",np.transpose(v))
print ("\n")

# e)
print ("e)")
print(np.dot(np.dot(u[:,:1],s[:1,:1]),np.transpose(v)[:1,:]))

U:
 [[-0.16492942  0.24497323]
 [-0.47164732 -0.45330644]
 [-0.33647055  0.82943965]
 [-0.00330585  0.16974659]
 [-0.79820031 -0.13310656]]
S:
 [[ 14.65163776   0.        ]
 [  0.           8.32643446]]
V^T:
 [[ 0.42615127  0.61500884  0.66344497]
 [-0.01460404 -0.72859799  0.68478587]]


e)
[[-1.02978864 -1.48616035 -1.60320558]
 [-2.94487812 -4.24996055 -4.58467382]
 [-2.10085952 -3.031898   -3.27068057]
 [-0.02064112 -0.02978864 -0.0321347 ]
 [-4.9838143  -7.19249261 -7.75895028]]
