In [1]:
import numpy as np
M = [[1,0,3],[3,7,2],[2,-2,8],[0,-1,1],[5,8,7]]
M = np.array(M, dtype = float)

# a)
print ("a)")
MTM = np.dot(np.transpose(M),M)
MMT = np.dot(M,np.transpose(M))

print ("MTM:\n",MTM)
print ("MMT:\n",MMT)
print ("\n")

eigvalueA, eigvectorA = np.linalg.eig(MTM)
eigvalueB, eigvectorB = np.linalg.eig(MMT)

# b)
print ("b)")
print ("eigvalueA:\n",eigvalueA)
print ("eigvalueB:\n",eigvalueB)
print ("\n")

# c)
print ("c)")
print ("eigvectorA:\n",eigvectorA)
print ("eigvectorB:\n",eigvectorB)
print ("\n")

# d)
print ("d)")
u,s,v = np.linalg.svd(M)
s =np.diag(s)
print ("U:\n",u)
print ("S:\n",s)
print ("V:\n",v)
print ("\n")

# e)
print ("e)")
def rankRApprox(matrix,r):
    u,s,v = np.linalg.svd(matrix)
    s =np.diag(s)
    approx_data=np.dot(np.dot(u[:,:r],s[:r,:r]),v[:r,:])
    return (np.linalg.norm(matrix - approx_data))

print ("Rank 1 approximation:\n",rankRApprox(M,1))
# ranks=[rankRApprox(i) for i in range(1,201)]
# plt.plot(range(1,201),ranks)
# plt.show()

a)
MTM:
 [[  39.   57.   60.]
 [  57.  118.   53.]
 [  60.   53.  127.]]
MMT:
 [[  10.    9.   26.    3.   26.]
 [   9.   62.    8.   -5.   85.]
 [  26.    8.   72.   10.   50.]
 [   3.   -5.   10.    2.   -1.]
 [  26.   85.   50.   -1.  138.]]


b)
eigvalueA:
 [  2.14670489e+02  -1.50990331e-14   6.93295108e+01]
eigvalueB:
 [  2.14670489e+02  -5.99520433e-15   6.93295108e+01   1.23720729e-14
  -7.24621456e-16]


c)
eigvectorA:
 [[ 0.42615127  0.90453403 -0.01460404]
 [ 0.61500884 -0.30151134 -0.72859799]
 [ 0.66344497 -0.30151134  0.68478587]]
eigvectorB:
 [[-0.16492942 -0.95539856  0.24497323 -0.06464508 -0.10671808]
 [-0.47164732 -0.03481209 -0.45330644  0.75010839 -0.04684757]
 [-0.33647055  0.27076072  0.82943965  0.3284142  -0.17364364]
 [-0.00330585  0.04409532  0.16974659  0.04591676  0.97063121]
 [-0.79820031  0.10366268 -0.13310656 -0.5685017   0.11890961]]


d)
U:
 [[-0.16492942 -0.24497323  0.94690858  0.02817617 -0.12392196]
 [-0.47164732  0.45330644 -0.06559072  0.1001021